
return { 
--    {'andrewradev/splitjoin.vim', keys = {"gJ", "gS"}},
--    {'dhruvasagar/vim-table-mode', cmd = "TableModeToggle"},
--    {'ervandew/supertab', event = "InsertEnter"},
--    {'jackMort/ChatGPT.nvim', cmd = "ChatGPT"},
--    {'JoosepAlviste/nvim-ts-context-commentstring', event = "BufReadPost"},
--    {'junegunn/fzf', run = function() vim.fn['fzf#install']() end, cmd = "FZF"},
--    {'junegunn/fzf.vim', after = 'fzf'},
--    {'junegunn/goyo.vim', cmd = "Goyo"},
--    {'junegunn/vim-easy-align', keys = {"ga"}},
--    {'majutsushi/tagbar', cmd = "TagbarToggle"},
--    {'mattn/emmet-vim', ft = {'html', 'css'}},
--    {'mcchrish/nnn.vim', cmd = "NnnPicker"},
--    {'muniftanjim/nui.nvim', module = "nui"},
--    {'neovim/nvim-lspconfig', event = "BufReadPre"},
--    {'ngmy/vim-rubocop', ft = "ruby"},
--    {'nvim-lua/completion-nvim', event = "InsertEnter"},
--    {'nvim-lua/plenary.nvim', module = "plenary"},
--    {'nvim-lua/popup.nvim', after = 'plenary.nvim'},
--    {'nvim-telescope/telescope.nvim', cmd = "Telescope"},
--    {'pechorin/any-jump.vim', cmd = "AnyJump"},
--    {'reedes/vim-wordy', cmd = "Wordy"},
--    {'sheerun/vim-polyglot', event = "VimEnter"},
--    {'t9md/vim-choosewin', keys = '-'},
--    {'vim-syntastic/syntastic', event = "BufReadPost"},
--    {'xolox/vim-misc', required_by = {'xolox/vim-notes'}},
--    {'xolox/vim-notes', cmd = "Notes"}
}
